### ISSUE TITLE
Any plans to add WinRT support?

### ISSUE THREAD

**Issue by jagobagascon** [zzl/go-win32api#1]
Hi! I was wondering if you had any plans to add WinRT support.

## A bit of background:
I've been trying to help with the Windows support of the [tinygo-org/bluetooth](https://github.com/tinygo-org/bluetooth) library, which uses the WinRT API. We are currently doing it manually, which requires reading the Windows IDL files and manually creating structs and methods that match those IDLs.

It is a very painful, error prone, boring task, and I'm desperately looking for a way to automatically generate those files from the source `winmd` files.

Windows support is being discussed on this issue: https://github.com/tinygo-org/bluetooth/issues/13

**Comment by zzl** [comment]
Hi @jagobagascon, Win32 and WinRT are two different worlds, this project will focus on classic win32 API binding, no WinRT support is planned. 
That said, I'm starting to look into the WinRT world. There might be a go-winrtapi project got created later, but not anytime soon.
If you're in a hurry, check out [this project](https://github.com/tdakkota/win32metadata), it seems to parse winmd files fine. You can try writing your own WinRt API generator based on it.

**Comment by jagobagascon** [comment]
Any effort towards creating a WinRT bindings Go library would be very much appreciated.

I'll check out the library, but I would say our use case doesn't need a full featured code generator, so any effort we make in code generation will probably be quite ad-hoc.

Just in case anyone reaches this issue, updates on this topic will probably be published here: https://github.com/tinygo-org/bluetooth/issues/13

Thank you for the quick response @zzl. I'm closing this now.

**Comment by zzl** [comment]
Hi @jagobagascon, I've just finished the aforementioned go-winrtapi, here's [the repo](https://github.com/zzl/go-winrtapi). Check it out to see if there's anything useful for your project.

**Comment by jagobagascon** [comment]
Wow! Just took a quick look at the code and looks really promissing. I'll try it as soon as I'm back from holidays.

Thanks a lot!
