### ISSUE TITLE
Passing NULL into windows functions

### ISSUE THREAD

**Issue by mdepot** [zzl/go-win32api#2]
When working with this module it wasn't obvious to me how one should pass a NULL into a windows function.  I came across this question while trying to work with GetDC() : https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getdc

This seems to work fine:
```
hwndDeskWin := win32.GetDesktopWindow()
hdcScreenDC := win32.GetDC(hwndDeskWin)
```

However, based on the web page above I should also just be able to pass a NULL to GetDC() to retrieve the DC for the entire screen.

Lacking docs or examples people might be tempted to try:

```
hdcScreenDC := win32.GetDC(uintptr(unsafe.Pointer(nil)))
```

...but that brings in unsafe and I'm not sure it's technically correct as seen by the windows API.

Please consider allowing this (or similar by type), as it would seem more intuitive:

```
hdcScreenDC := win32.GetDC(win32.NULL)
```

**Comment by zzl** [comment]
Yes `uintptr(unsafe.Pointer(nil))` is technically correct, you could as well use `uintptr(0)` or even a single `0`, they're all valid representation of a NULL uintptr value. 
Adding a NULL constant to the win32 API might be a good idea, I'll consider that. Thanks for your feedback.

**Comment by zzl** [comment]
Just released a version that includes win32.NULL. Issue closed.
