### ISSUE TITLE
BITMAPINFOHEADER biCompression field type

### ISSUE THREAD

**Issue by mdepot** [zzl/go-win32api#3]
Regarding the BITMAPINFOHEADER structure documented here:
https://learn.microsoft.com/en-us/windows/win32/api/wingdi/ns-wingdi-bitmapinfoheader

The field biCompression is a DWORD on the Microsoft side, and has a number of BI_* values that can be assigned.

In go-win32api those fields are defined within Graphics.Gdi.go, ( BI_RGB for example ), and they are given the go type int32.  These are intended to be assigned to the BiCompression field of BITMAPINFOHEADER, which is also defined in Graphics.Gdi.go.
However the BiCompression field has been given the go type uint32, which causes a type mismatch error on assignment:

var bi win32.BITMAPINFOHEADER
bi.BiCompression = win32.BI_RGB
> cannot use win32.BI_RGB (constant 0 of type int32) as uint32 value in assignment

Is this mismatch unintended, or are people actually supposed to be casting this field?  Thanks

**Comment by mdepot** [comment]
I looked at the win32metadata and saw System.Drawing.NativeMethods and Windows.Win32.DirectShow both use uint for biCompression, and that BI_RGB uses int, so I gather it's not an issue to be dealt with here in go-win32api.

For others finding similar problems, you might try using ILSpy as mentioned on the win32metadata page to see what's coming in from upstream.  https://github.com/microsoft/win32metadata

**Comment by zzl** [comment]
> I looked at the win32metadata and saw System.Drawing.NativeMethods and Windows.Win32.DirectShow both use uint for biCompression, and that BI_RGB uses int, so I gather it's not an issue to be dealt with here in go-win32api.
> 
> For others finding similar problems, you might try using ILSpy as mentioned on the win32metadata page to see what's coming in from upstream. https://github.com/microsoft/win32metadata

Hi @mdepot, sorry for the late reply.

Yes the problem roots from the Win32Metadata definitions. However, the [latest Win32Metadata](https://www.nuget.org/packages/Microsoft.Windows.SDK.Win32Metadata/41.0.25-preview) has resolved the inconsistent types by using enums. I've released a new version of go-win32api that reflects the changes. Check it out to see if it helps.

**Comment by mdepot** [comment]
Thank you.  See also https://github.com/microsoft/win32metadata/issues/1442, which I had posted prior to your last update.

**Comment by zzl** [comment]
> Thank you. See also [microsoft/win32metadata#1442](https://github.com/microsoft/win32metadata/issues/1442), which I had posted prior to your last update.

There might be different API sets introduced at different time that reuse/extend the bitmap compression flag that results in different enumeration values and documentations, just guess. Anyway, let people at Microsoft worry about the consistency problems, we have little to do about it.
