### ISSUE TITLE
Missing functions from propsys.h (e.g. SHGetPropertyStoreFromParsingName, PSFormatForDisplayAlloc etc.)

### ISSUE THREAD

**Issue by fgimian** [zzl/go-win32api#4]
Hey there, firstly thank you so so much for your work on this library! 😄 

I'm using the `SHGetPropertyStoreFromParsingName` function to obtain an `IPropertyStore` with some properties for font files.  There are some useful functions which are required to manipulate properties which appear to be missing from this library.  I believe that all functions from [propsys.h](https://learn.microsoft.com/en-us/windows/win32/api/propsys/) may have been missed such as the following:

- PSFormatForDisplayAlloc
- PSGetNameFromPropertyKey
- PSGetPropertyKeyFromName

Any help would be greatly appreciated!  In the meantime, I'll attempt to use syscall to call them. 😄 
Fotis

**Comment by zzl** [comment]
Hi,
The library is not designed to be exhaustive: it only includes commonly used APIs, to avoid making the code base overly large and overwhelming IDEs.
If you find that the APIs you need are not included, you can generate them yourself using the winapi-gen tool. For your convenience, I have already used this tool to generate the functions and constants related to the Windows Property System, and I have added an example called 'propertystore' to the examples folder. I hope this helps!

**Comment by fgimian** [comment]
> Hi, The library is not designed to be exhaustive: it only includes commonly used APIs, to avoid making the code base overly large and overwhelming IDEs. If you find that the APIs you need are not included, you can generate them yourself using the winapi-gen tool. For your convenience, I have already used this tool to generate the functions and constants related to the Windows Property System, and I have added an example called 'propertystore' to the examples folder. I hope this helps!

Beautiful, thank you so much.  I totally understand where you're coming from as the library could grow to be huge.

Really appreciate your reply and help! 😄 

I'll close this issue now
Fotis
